<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookingSeeder extends Seeder
{
    public function run()
    {
        DB::table('bookings')->insert([
            [
                'booking_number' => 422701608,
                'service_id' => 1,
                'user_id' => 3,
                'booking_from' => '2024-02-17',
                'booking_to' => '2024-02-19',
                'event_type_id' => 1,
                'number_of_guest' => 200,
                'state_id' => 28,
                'city_name' => 'Raikot',
                'message' => 'rytriyu\r\nuytuyi\r\n\r\njoyuutuyfh',
                'booking_date' => '2024-02-16 06:58:08',
                'remark' => 'Approved',
                'status' => 'Approved',
                'updation_date' => '2024-03-02 05:06:50',
                'payment_proof' => null,
                'payment_proof_type' => null,
                'payment_proof_size' => null,
            ],
            [
                'booking_number' => 697339619,
                'service_id' => 2,
                'user_id' => 4,
                'booking_from' => '2024-02-20',
                'booking_to' => '2024-02-22',
                'event_type_id' => 2,
                'number_of_guest' => 200,
                'state_id' => 13,
                'city_name' => 'Rohtak',
                'message' => 'NA',
                'booking_date' => '2024-02-19 15:24:38',
                'remark' => 'Your booking is cancelled',
                'status' => 'Cancelled',
                'updation_date' => '2024-03-02 05:06:57',
                'payment_proof' => null,
                'payment_proof_type' => null,
                'payment_proof_size' => null,
            ],
            [
                'booking_number' => 347642822,
                'service_id' => 4,
                'user_id' => 5,
                'booking_from' => '2024-02-27',
                'booking_to' => '2024-02-28',
                'event_type_id' => 2,
                'number_of_guest' => 25,
                'state_id' => 31,
                'city_name' => 'Coimbatore North',
                'message' => 'NA',
                'booking_date' => '2024-02-19 17:51:30',
                'remark' => 'Approved',
                'status' => 'Approved',
                'updation_date' => '2024-03-02 05:07:07',
                'payment_proof' => null,
                'payment_proof_type' => null,
                'payment_proof_size' => null,
            ],
            [
                'booking_number' => 144316724,
                'service_id' => 1,
                'user_id' => 5,
                'booking_from' => '2024-03-14',
                'booking_to' => '2024-03-16',
                'event_type_id' => 1,
                'number_of_guest' => 20,
                'state_id' => 10,
                'city_name' => 'Karol Bagh',
                'message' => 'NA',
                'booking_date' => '2024-03-02 04:42:09',
                'remark' => 'Okai',
                'status' => 'Approved',
                'updation_date' => '2024-10-20 04:33:12',
                'payment_proof' => null,
                'payment_proof_type' => null,
                'payment_proof_size' => null,
            ],
            [
                'booking_number' => 901857931,
                'service_id' => 1,
                'user_id' => 5,
                'booking_from' => '2024-10-20',
                'booking_to' => '2024-10-20',
                'event_type_id' => 3,
                'number_of_guest' => 4,
                'state_id' => 5,
                'city_name' => 'Islamnagar Aliganj',
                'message' => 'Let\'s go',
                'booking_date' => '2024-10-20 04:30:14',
                'remark' => null,
                'status' => null,
                'updation_date' => null,
                'payment_proof' => null,
                'payment_proof_type' => null,
                'payment_proof_size' => null,
            ],
        ]);
    }
}
